-- Run this in Supabase SQL Editor to set up the tables

-- 1. RESERVATIONS Table
CREATE TABLE IF NOT EXISTS reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  date DATE,
  time TEXT,
  type TEXT,
  deck TEXT,
  request_content TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. FAQs Table
CREATE TABLE IF NOT EXISTS faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. REVIEWS Table
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  name TEXT NOT NULL,
  rating INTEGER DEFAULT 5,
  comment TEXT,
  product TEXT DEFAULT 'tarrot',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. USERS Table (for Customers & Admin)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  password TEXT, -- Note: In a real app, use Supabase Auth instead!
  role TEXT DEFAULT 'user', -- 'admin' or 'user'
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. VENDORS Table (from previous request context, ensuring it exists)
CREATE TABLE IF NOT EXISTS vendors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  contact TEXT,
  location TEXT,
  image TEXT,
  gallery_images TEXT, -- Stored as JSON string or array
  is_featured BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'partner',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. SETTLEMENTS Table (Admin context)
CREATE TABLE IF NOT EXISTS settlements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id BIGINT REFERENCES vendors(id),
  amount DECIMAL(10, 2),
  status TEXT DEFAULT 'pending',
  due_date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. ENABLE RLS (Row Level Security) - Important for Client-side usage
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE settlements ENABLE ROW LEVEL SECURITY;

-- 8. POLICIES (Simple Public Access for this Demo)
-- Allow anyone to read FAQs, Vendors, Reviews
CREATE POLICY "Public Read FAQs" ON faqs FOR SELECT TO anon USING (true);
CREATE POLICY "Public Read Vendors" ON vendors FOR SELECT TO anon USING (true);
CREATE POLICY "Public Read Reviews" ON reviews FOR SELECT TO anon USING (true);

-- Allow anyone to create Reservations
CREATE POLICY "Public Create Reservations" ON reservations FOR INSERT TO anon WITH CHECK (true);
-- Allow anyone to read Reservations (for checking availability) - In prod, restrict this!
CREATE POLICY "Public Read Reservations" ON reservations FOR SELECT TO anon USING (true);

-- Allow anyone to create Users (Sign up)
CREATE POLICY "Public Create Users" ON users FOR INSERT TO anon WITH CHECK (true);

-- Allow admins full access (This is tricky without Supabase Auth, so for now we allow All to All for demo simplification or specific role checks if using Auth)
-- FOR DEMO/DEV PURPOSE ONLY: Allow all access to everything for anon (so Admin panel works without Auth migration)
-- WARNING: This is insecure for production.
CREATE POLICY "Public All Access Reservations" ON reservations FOR ALL TO anon USING (true);
CREATE POLICY "Public All Access FAQs" ON faqs FOR ALL TO anon USING (true);
CREATE POLICY "Public All Access Users" ON users FOR ALL TO anon USING (true);
CREATE POLICY "Public All Access Vendors" ON vendors FOR ALL TO anon USING (true);
CREATE POLICY "Public All Access Reviews" ON reviews FOR ALL TO anon USING (true);

-- Seed Initial Data (FAQs)
INSERT INTO faqs (question, answer) VALUES
('상담 전 미리 준비해야 할 것이 있나요?', '특별히 준비할 것은 없지만, 상담받고 싶은 질문을 명확하게 2~3가지 정도 미리 정리해두시면 더욱 심도 있는 상담이 가능합니다.'),
('예약 후 취소 및 환불 규정은 어떻게 되나요?', '상담 24시간 전 취소 시 전액 환불이 가능합니다. 이후 취소 시에는 예약 상품에 따라 수수료가 발생할 수 있습니다.'),
('여러 명이 같이 상담받을 수 있나요?', '네, 방문 상담 시 최대 2인까지 가능합니다. 다만, 상담 시간이 추가될 수 있으므로 예약 시 미리 말씀해주시기 바랍니다.')
ON CONFLICT DO NOTHING;

-- Seed Admin User (Password: admin123)
INSERT INTO users (name, email, password, role) VALUES ('Admin', 'admin@example.com', 'admin123', 'admin');

-- Seed Sample Vendors (for Home & Category pages)
INSERT INTO vendors (name, category, contact, location, is_featured, status, image) VALUES
('Lumiere Studio', 'Studio', '02-123-4567', 'Seoul, Gangnam', true, 'partner', 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=2070'),
('Grace Kelly Dress', 'Dress', '02-987-6543', 'Seoul, Cheongdam', true, 'partner', 'https://images.unsplash.com/photo-1594539933397-043f77341d3d?q=80&w=2000'),
('Pure Makeup', 'Makeup', '02-555-1234', 'Seoul, Sinsa', false, 'partner', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=2000')
ON CONFLICT DO NOTHING;
